version: "2"
services:
  app:
    container_name: app
    build: .
    links:
        - mongo
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
      - ../apache-tomcat-9.0.5/webapps/webserver:/opt/app/tomcat
      - /opt/app/node_modules

  mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
